FROM node:alpine as builder
WORKDIR as '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
#/app/build will have build folder
FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html
